#!/bin/bash

# hit this up with http://localhost:8500/ui/
sudo rm -rf  /data:/data/docker/consul*
echo "##############################################################"
echo "# Now run the following commands"
echo "cd terraform"
echo "sudo terraform apply"

